Import the needed python packages

In [2]:
import tensorflow as tf
import keras
import matplotlib as plt
import seaborn as sb
import pandas as pd
import numpy as np
import scipy as sy
import pickle

Load preprocessed Kaggle data

In [3]:
file_train = open("data/training_dataset.pickle",'rb')
trainingdata = pickle.load(file_train)
train_data, train_label = trainingdata['data'], trainingdata['label']

file_validation = open("data/validation_dataset.pickle",'rb')
validationdata = pickle.load(file_validation)
valid_data, valid_label = validationdata['data'], validationdata['label']

Create a the baseline CNN model

In [52]:
# create a sequential model
model = tf.keras.Sequential()

# add layers
model.add(tf.keras.layers.Input((100,100,3)))
model.add(tf.keras.layers.Conv2D(16, (3,3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D((2,2)))
model.add(tf.keras.layers.Conv2D(16, (3,3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D((2,2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [53]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 98, 98, 16)        448       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 49, 49, 16)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 47, 47, 16)        2320      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 23, 23, 16)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 8464)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                541760    
_________________________________________________________________
dense_3 (Dense)              (None, 1)                

In [54]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(train_label)
train_label = le.transform(train_label)

le.fit(valid_label)
valid_label = le.transform(valid_label)

In [55]:
print(train_label)
print(valid_label)

[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]


In [56]:
# Training the network
model.compile(optimizer = "rmsprop", loss = "binary_crossentropy", metrics = ["accuracy"])
model.fit(x = train_data, y = train_label, batch_size = 64, epochs = 10)
test_loss, test_acc = model.evaluate(x = valid_data, y = valid_label)

40/40 [==============================] - 2s 53ms/step - loss: 0.4794 - accuracy: 0.7686


In [32]:
np.bincount(valid_label)

array([502, 777], dtype=int64)

In [38]:
502/(777+502)

0.3924941360437842

In [40]:
test_acc

0.3924941420555115